[package]
name = "granularity_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.30"
quote = "1.0.32"
syn = { version = "2.0.27", features = ["full"] }
